FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1
WORKDIR /
USER root
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
#RUN chown 1000:1000 elasticsearch
RUN chmod 777 -R /usr/share/elasticsearch
